  0%|          | 0/536901 [00:00<?, ?it/s]

===== HYPERPARAMETERS =====
model_name =  linear
device_type = cuda
batch_size = 128
epochs = 10
learning_rate = 0.001
weight_decay = 0
===========================
  0%|          | 0/536901 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "/scratch/ik1125/4IAR-nns/load_train.py", line 106, in <module>
    main(model_name=args.model_name, model_version=args.model_version, num_layers=args.num_layers, num_units=args.num_units,
  File "/scratch/ik1125/4IAR-nns/load_train.py", line 58, in main
    train(net, batch_size=batch_size, n_epochs=n_epochs, learning_rate=learning_rate,
  File "/scratch/ik1125/4IAR-nns/training.py", line 60, in train
    for data in tqdm.tqdm(train_loader):
  File "/ext3/4IAR-conda/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/ext3/4IAR-conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/ext3/4IAR-conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/ext3/4IAR-conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/ext3/4IAR-conda/lib/python3.9/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/ext3/4IAR-conda/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/ext3/4IAR-conda/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ext3/4IAR-conda/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/scratch/ik1125/4IAR-nns/custom_dataset.py", line 32, in __getitem__
    game_index = bisect(self.gamestart_index, index)
TypeError: 'module' object is not callable

